<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250116141157 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE character_eidolons_media DROP FOREIGN KEY FK_90003B1EEA9FDD75');
        $this->addSql('ALTER TABLE character_eidolons_media DROP FOREIGN KEY FK_90003B1E18E42D5D');
        $this->addSql('DROP TABLE character_eidolons_media');
        $this->addSql('ALTER TABLE ascension_mats ADD four_star_name VARCHAR(255) NOT NULL, ADD three_star_name VARCHAR(255) NOT NULL, ADD two_star_name VARCHAR(255) NOT NULL, ADD released TINYINT(1) NOT NULL, ADD announced TINYINT(1) NOT NULL, DROP asc_mat_four_star_name, DROP asc_mat_three_star_name, DROP asc_mat_two_star_name, DROP asc_mat_released, DROP asc_mat_announced');
        $this->addSql('ALTER TABLE base_character DROP FOREIGN KEY FK_205621B9F5875707');
        $this->addSql('ALTER TABLE base_character DROP FOREIGN KEY FK_205621B9CF3094AD');
        $this->addSql('ALTER TABLE base_character DROP FOREIGN KEY FK_205621B9B0C9D656');
        $this->addSql('ALTER TABLE base_character DROP FOREIGN KEY FK_205621B9ACE90CAE');
        $this->addSql('ALTER TABLE base_character DROP FOREIGN KEY FK_205621B97D90850D');
        $this->addSql('ALTER TABLE base_character DROP FOREIGN KEY FK_205621B91C8E87F1');
        $this->addSql('ALTER TABLE base_character DROP FOREIGN KEY FK_205621B914B0F2E9');
        $this->addSql('DROP INDEX UNIQ_205621B91C8E87F1 ON base_character');
        $this->addSql('DROP INDEX IDX_205621B9B0C9D656 ON base_character');
        $this->addSql('DROP INDEX IDX_205621B9ACE90CAE ON base_character');
        $this->addSql('DROP INDEX IDX_205621B9CF3094AD ON base_character');
        $this->addSql('DROP INDEX IDX_205621B914B0F2E9 ON base_character');
        $this->addSql('DROP INDEX IDX_205621B9F5875707 ON base_character');
        $this->addSql('DROP INDEX IDX_205621B97D90850D ON base_character');
        $this->addSql('ALTER TABLE base_character ADD path_id INT DEFAULT NULL, ADD type_id INT DEFAULT NULL, ADD asc_mats_id INT DEFAULT NULL, ADD boss_mat_id INT DEFAULT NULL, ADD weekly_mat_id INT DEFAULT NULL, ADD trace_mats_id INT DEFAULT NULL, ADD name VARCHAR(255) NOT NULL, ADD slug VARCHAR(255) NOT NULL, ADD rarity VARCHAR(255) NOT NULL, ADD released TINYINT(1) NOT NULL, ADD announced TINYINT(1) NOT NULL, ADD release_version VARCHAR(255) DEFAULT NULL, ADD banner_name VARCHAR(255) DEFAULT NULL, DROP character_path_id, DROP character_type_id, DROP eidolons_id, DROP character_asc_mats_id, DROP character_boss_mat_id, DROP character_weekly_mat_id, DROP character_trace_mats_id, DROP character_name, DROP character_slug, DROP character_rarity, DROP character_released, DROP character_announced, DROP character_release_version, DROP character_banner_name, CHANGE character_release_date release_date DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE base_character ADD CONSTRAINT FK_205621B9D96C566B FOREIGN KEY (path_id) REFERENCES path (id)');
        $this->addSql('ALTER TABLE base_character ADD CONSTRAINT FK_205621B9C54C8C93 FOREIGN KEY (type_id) REFERENCES type (id)');
        $this->addSql('ALTER TABLE base_character ADD CONSTRAINT FK_205621B9CB5A3E01 FOREIGN KEY (asc_mats_id) REFERENCES ascension_mats (id)');
        $this->addSql('ALTER TABLE base_character ADD CONSTRAINT FK_205621B910DA5845 FOREIGN KEY (boss_mat_id) REFERENCES boss_mat (id)');
        $this->addSql('ALTER TABLE base_character ADD CONSTRAINT FK_205621B9C136EA7E FOREIGN KEY (weekly_mat_id) REFERENCES weekly_mat (id)');
        $this->addSql('ALTER TABLE base_character ADD CONSTRAINT FK_205621B949213874 FOREIGN KEY (trace_mats_id) REFERENCES trace_mats (id)');
        $this->addSql('CREATE INDEX IDX_205621B9D96C566B ON base_character (path_id)');
        $this->addSql('CREATE INDEX IDX_205621B9C54C8C93 ON base_character (type_id)');
        $this->addSql('CREATE INDEX IDX_205621B9CB5A3E01 ON base_character (asc_mats_id)');
        $this->addSql('CREATE INDEX IDX_205621B910DA5845 ON base_character (boss_mat_id)');
        $this->addSql('CREATE INDEX IDX_205621B9C136EA7E ON base_character (weekly_mat_id)');
        $this->addSql('CREATE INDEX IDX_205621B949213874 ON base_character (trace_mats_id)');
        $this->addSql('ALTER TABLE boss_mat DROP FOREIGN KEY FK_41390997D6CAE9E8');
        $this->addSql('ALTER TABLE boss_mat DROP FOREIGN KEY FK_41390997D0FF67F');
        $this->addSql('ALTER TABLE boss_mat DROP FOREIGN KEY FK_41390997473FB249');
        $this->addSql('DROP INDEX UNIQ_41390997D6CAE9E8 ON boss_mat');
        $this->addSql('DROP INDEX UNIQ_41390997D0FF67F ON boss_mat');
        $this->addSql('DROP INDEX IDX_41390997473FB249 ON boss_mat');
        $this->addSql('ALTER TABLE boss_mat ADD icon_id INT DEFAULT NULL, ADD stagnant_shadow_id INT DEFAULT NULL, ADD type_id INT DEFAULT NULL, ADD released TINYINT(1) NOT NULL, ADD announced TINYINT(1) NOT NULL, DROP boss_mat_icon_id, DROP boss_mat_stagnant_shadow_id, DROP boss_mat_type_id, DROP boss_mat_released, DROP boss_mat_announced, CHANGE boss_mat_name name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE boss_mat ADD CONSTRAINT FK_4139099754B9D732 FOREIGN KEY (icon_id) REFERENCES media (id)');
        $this->addSql('ALTER TABLE boss_mat ADD CONSTRAINT FK_413909974EF5897C FOREIGN KEY (stagnant_shadow_id) REFERENCES stagnant_shadow (id)');
        $this->addSql('ALTER TABLE boss_mat ADD CONSTRAINT FK_41390997C54C8C93 FOREIGN KEY (type_id) REFERENCES type (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_4139099754B9D732 ON boss_mat (icon_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_413909974EF5897C ON boss_mat (stagnant_shadow_id)');
        $this->addSql('CREATE INDEX IDX_41390997C54C8C93 ON boss_mat (type_id)');
        $this->addSql('ALTER TABLE character_eidolons ADD character_kit_id INT DEFAULT NULL, ADD icon_id INT DEFAULT NULL, ADD name VARCHAR(255) NOT NULL, ADD number VARCHAR(255) DEFAULT NULL, ADD pull_worth VARCHAR(255) DEFAULT NULL, ADD recommendation LONGTEXT DEFAULT NULL, DROP eidolon_one, DROP eidolon_two, DROP eidolon_three, DROP eidolon_four, DROP eidolon_five, DROP eidolon_six, CHANGE eidolon_stop_point description LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE character_eidolons ADD CONSTRAINT FK_33089EC899CCA37C FOREIGN KEY (character_kit_id) REFERENCES character_kit (id)');
        $this->addSql('ALTER TABLE character_eidolons ADD CONSTRAINT FK_33089EC854B9D732 FOREIGN KEY (icon_id) REFERENCES media (id)');
        $this->addSql('CREATE INDEX IDX_33089EC899CCA37C ON character_eidolons (character_kit_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_33089EC854B9D732 ON character_eidolons (icon_id)');
        $this->addSql('ALTER TABLE character_kit DROP FOREIGN KEY FK_133E43869F27DED4');
        $this->addSql('DROP INDEX UNIQ_133E43869F27DED4 ON character_kit');
        $this->addSql('ALTER TABLE character_kit CHANGE character_talent_id talent_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE character_kit ADD CONSTRAINT FK_133E438618777CEF FOREIGN KEY (talent_id) REFERENCES character_talent (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_133E438618777CEF ON character_kit (talent_id)');
        $this->addSql('ALTER TABLE character_stories DROP FOREIGN KEY FK_F52E1D6295FABCD7');
        $this->addSql('DROP INDEX UNIQ_F52E1D6295FABCD7 ON character_stories');
        $this->addSql('ALTER TABLE character_stories CHANGE character_stories_character_id character_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE character_stories ADD CONSTRAINT FK_F52E1D621136BE75 FOREIGN KEY (character_id) REFERENCES base_character (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F52E1D621136BE75 ON character_stories (character_id)');
        $this->addSql('ALTER TABLE character_voiceline DROP FOREIGN KEY FK_DAE759C8E37CC563');
        $this->addSql('DROP INDEX IDX_DAE759C8E37CC563 ON character_voiceline');
        $this->addSql('ALTER TABLE character_voiceline CHANGE voiceline_character_id character_id INT DEFAULT NULL, CHANGE voiceline_name name VARCHAR(255) NOT NULL, CHANGE voiceline_content content LONGTEXT DEFAULT NULL, CHANGE voiceline_category category VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE character_voiceline ADD CONSTRAINT FK_DAE759C81136BE75 FOREIGN KEY (character_id) REFERENCES base_character (id)');
        $this->addSql('CREATE INDEX IDX_DAE759C81136BE75 ON character_voiceline (character_id)');
        $this->addSql('ALTER TABLE crimson_calyx DROP FOREIGN KEY FK_21EE9C972F1B3052');
        $this->addSql('DROP INDEX IDX_21EE9C972F1B3052 ON crimson_calyx');
        $this->addSql('ALTER TABLE crimson_calyx CHANGE crimson_calyx_location_id location_id INT DEFAULT NULL, CHANGE crimson_calyx_name name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE crimson_calyx ADD CONSTRAINT FK_21EE9C9764D218E FOREIGN KEY (location_id) REFERENCES location (id)');
        $this->addSql('CREATE INDEX IDX_21EE9C9764D218E ON crimson_calyx (location_id)');
        $this->addSql('ALTER TABLE echo_of_war DROP FOREIGN KEY FK_A4D428A53206CF33');
        $this->addSql('ALTER TABLE echo_of_war DROP FOREIGN KEY FK_A4D428A540A0AE73');
        $this->addSql('ALTER TABLE echo_of_war DROP FOREIGN KEY FK_A4D428A56B48C239');
        $this->addSql('DROP INDEX UNIQ_A4D428A53206CF33 ON echo_of_war');
        $this->addSql('DROP INDEX UNIQ_A4D428A540A0AE73 ON echo_of_war');
        $this->addSql('DROP INDEX IDX_A4D428A56B48C239 ON echo_of_war');
        $this->addSql('ALTER TABLE echo_of_war ADD icon_id INT DEFAULT NULL, ADD boss_id INT DEFAULT NULL, ADD location_id INT DEFAULT NULL, DROP echo_of_war_icon_id, DROP echo_of_war_boss_id, DROP echo_of_war_location_id, CHANGE echo_of_war_name name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE echo_of_war ADD CONSTRAINT FK_A4D428A554B9D732 FOREIGN KEY (icon_id) REFERENCES media (id)');
        $this->addSql('ALTER TABLE echo_of_war ADD CONSTRAINT FK_A4D428A5261FB672 FOREIGN KEY (boss_id) REFERENCES echos_boss (id)');
        $this->addSql('ALTER TABLE echo_of_war ADD CONSTRAINT FK_A4D428A564D218E FOREIGN KEY (location_id) REFERENCES location (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A4D428A554B9D732 ON echo_of_war (icon_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A4D428A5261FB672 ON echo_of_war (boss_id)');
        $this->addSql('CREATE INDEX IDX_A4D428A564D218E ON echo_of_war (location_id)');
        $this->addSql('ALTER TABLE echos_boss DROP FOREIGN KEY FK_E7150372B1EF9B71');
        $this->addSql('DROP INDEX UNIQ_E7150372B1EF9B71 ON echos_boss');
        $this->addSql('ALTER TABLE echos_boss CHANGE echo_boss_icon_id icon_id INT DEFAULT NULL, CHANGE echo_boss_name name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE echos_boss ADD CONSTRAINT FK_E715037254B9D732 FOREIGN KEY (icon_id) REFERENCES media (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E715037254B9D732 ON echos_boss (icon_id)');
        $this->addSql('ALTER TABLE elite_enemy DROP FOREIGN KEY FK_40EEB329A3E838B4');
        $this->addSql('DROP INDEX UNIQ_40EEB329A3E838B4 ON elite_enemy');
        $this->addSql('ALTER TABLE elite_enemy CHANGE elite_enemy_icon_id icon_id INT DEFAULT NULL, CHANGE elite_enemy_name name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE elite_enemy ADD CONSTRAINT FK_40EEB32954B9D732 FOREIGN KEY (icon_id) REFERENCES media (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_40EEB32954B9D732 ON elite_enemy (icon_id)');
        $this->addSql('ALTER TABLE golden_calyx DROP FOREIGN KEY FK_2CDBA20B434731FE');
        $this->addSql('DROP INDEX IDX_2CDBA20B434731FE ON golden_calyx');
        $this->addSql('ALTER TABLE golden_calyx CHANGE golden_calyx_location_id location_id INT DEFAULT NULL, CHANGE golden_calyx_name name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE golden_calyx ADD CONSTRAINT FK_2CDBA20B64D218E FOREIGN KEY (location_id) REFERENCES location (id)');
        $this->addSql('CREATE INDEX IDX_2CDBA20B64D218E ON golden_calyx (location_id)');
        $this->addSql('ALTER TABLE light_cone DROP FOREIGN KEY FK_3CA8009485B95996');
        $this->addSql('ALTER TABLE light_cone DROP FOREIGN KEY FK_3CA800942A989BC3');
        $this->addSql('ALTER TABLE light_cone DROP FOREIGN KEY FK_3CA8009416513B1D');
        $this->addSql('DROP INDEX IDX_3CA8009485B95996 ON light_cone');
        $this->addSql('DROP INDEX IDX_3CA800942A989BC3 ON light_cone');
        $this->addSql('DROP INDEX IDX_3CA8009416513B1D ON light_cone');
        $this->addSql('ALTER TABLE light_cone ADD path_id INT DEFAULT NULL, ADD asc_mats_id INT DEFAULT NULL, ADD trace_mats_id INT DEFAULT NULL, ADD name VARCHAR(255) NOT NULL, ADD slug VARCHAR(255) NOT NULL, ADD rarity VARCHAR(255) NOT NULL, ADD base_atk INT DEFAULT NULL, ADD base_def INT DEFAULT NULL, ADD base_hp INT DEFAULT NULL, ADD story LONGTEXT DEFAULT NULL, ADD superimposition_one LONGTEXT DEFAULT NULL, ADD superimposition_two LONGTEXT DEFAULT NULL, ADD superimposition_three LONGTEXT DEFAULT NULL, ADD superimposition_four LONGTEXT DEFAULT NULL, ADD superimposition_five LONGTEXT DEFAULT NULL, ADD skill_name VARCHAR(255) DEFAULT NULL, ADD announced TINYINT(1) NOT NULL, ADD released TINYINT(1) NOT NULL, ADD obtainable VARCHAR(255) NOT NULL, ADD release_version VARCHAR(255) DEFAULT NULL, DROP lc_path_id, DROP lc_asc_mats_id, DROP lc_trace_mats_id, DROP lc_name, DROP lc_slug, DROP lc_rarity, DROP lc_base_atk, DROP lc_base_def, DROP lc_base_hp, DROP lc_story, DROP lc_skill_one, DROP lc_skill_two, DROP lc_skill_three, DROP lc_skill_four, DROP lc_skill_five, DROP lc_skill_name, DROP lc_announced, DROP lc_released, DROP lc_obtainable, DROP lc_release_version');
        $this->addSql('ALTER TABLE light_cone ADD CONSTRAINT FK_3CA80094D96C566B FOREIGN KEY (path_id) REFERENCES path (id)');
        $this->addSql('ALTER TABLE light_cone ADD CONSTRAINT FK_3CA80094CB5A3E01 FOREIGN KEY (asc_mats_id) REFERENCES ascension_mats (id)');
        $this->addSql('ALTER TABLE light_cone ADD CONSTRAINT FK_3CA8009449213874 FOREIGN KEY (trace_mats_id) REFERENCES trace_mats (id)');
        $this->addSql('CREATE INDEX IDX_3CA80094D96C566B ON light_cone (path_id)');
        $this->addSql('CREATE INDEX IDX_3CA80094CB5A3E01 ON light_cone (asc_mats_id)');
        $this->addSql('CREATE INDEX IDX_3CA8009449213874 ON light_cone (trace_mats_id)');
        $this->addSql('ALTER TABLE location DROP FOREIGN KEY FK_5E9E89CBBAFCC496');
        $this->addSql('DROP INDEX UNIQ_5E9E89CBBAFCC496 ON location');
        $this->addSql('ALTER TABLE location ADD name VARCHAR(255) NOT NULL, ADD world VARCHAR(255) NOT NULL, DROP location_name, DROP location_world, CHANGE location_icon_id icon_id INT DEFAULT NULL, CHANGE location_released released TINYINT(1) NOT NULL, CHANGE location_description description LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE location ADD CONSTRAINT FK_5E9E89CB54B9D732 FOREIGN KEY (icon_id) REFERENCES media (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5E9E89CB54B9D732 ON location (icon_id)');
        $this->addSql('ALTER TABLE media CHANGE media_name name VARCHAR(255) NOT NULL, CHANGE image_role role VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE normal_enemy DROP FOREIGN KEY FK_B638B9F3935657E1');
        $this->addSql('DROP INDEX UNIQ_B638B9F3935657E1 ON normal_enemy');
        $this->addSql('ALTER TABLE normal_enemy CHANGE normal_enemy_icon_id icon_id INT DEFAULT NULL, CHANGE normal_enemy_name name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE normal_enemy ADD CONSTRAINT FK_B638B9F354B9D732 FOREIGN KEY (icon_id) REFERENCES media (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B638B9F354B9D732 ON normal_enemy (icon_id)');
        $this->addSql('ALTER TABLE path DROP FOREIGN KEY FK_B548B0F930FE11B');
        $this->addSql('DROP INDEX UNIQ_B548B0F930FE11B ON path');
        $this->addSql('ALTER TABLE path CHANGE path_icon_id icon_id INT DEFAULT NULL, CHANGE path_name name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE path ADD CONSTRAINT FK_B548B0F54B9D732 FOREIGN KEY (icon_id) REFERENCES media (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B548B0F54B9D732 ON path (icon_id)');
        $this->addSql('ALTER TABLE stagnant_shadow DROP FOREIGN KEY FK_2D8BA4CCF33A9CE4');
        $this->addSql('ALTER TABLE stagnant_shadow DROP FOREIGN KEY FK_2D8BA4CC819CFDA4');
        $this->addSql('ALTER TABLE stagnant_shadow DROP FOREIGN KEY FK_2D8BA4CC21A15829');
        $this->addSql('DROP INDEX UNIQ_2D8BA4CCF33A9CE4 ON stagnant_shadow');
        $this->addSql('DROP INDEX UNIQ_2D8BA4CC819CFDA4 ON stagnant_shadow');
        $this->addSql('DROP INDEX IDX_2D8BA4CC21A15829 ON stagnant_shadow');
        $this->addSql('ALTER TABLE stagnant_shadow ADD icon_id INT DEFAULT NULL, ADD boss_id INT DEFAULT NULL, ADD location_id INT DEFAULT NULL, DROP stagnant_shadow_icon_id, DROP stagnant_shadow_boss_id, DROP stagnant_shadow_location_id, CHANGE stagnant_shadow_name name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE stagnant_shadow ADD CONSTRAINT FK_2D8BA4CC54B9D732 FOREIGN KEY (icon_id) REFERENCES media (id)');
        $this->addSql('ALTER TABLE stagnant_shadow ADD CONSTRAINT FK_2D8BA4CC261FB672 FOREIGN KEY (boss_id) REFERENCES elite_enemy (id)');
        $this->addSql('ALTER TABLE stagnant_shadow ADD CONSTRAINT FK_2D8BA4CC64D218E FOREIGN KEY (location_id) REFERENCES location (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2D8BA4CC54B9D732 ON stagnant_shadow (icon_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2D8BA4CC261FB672 ON stagnant_shadow (boss_id)');
        $this->addSql('CREATE INDEX IDX_2D8BA4CC64D218E ON stagnant_shadow (location_id)');
        $this->addSql('ALTER TABLE trace_mats DROP FOREIGN KEY FK_841E84D4950B42A7');
        $this->addSql('ALTER TABLE trace_mats DROP FOREIGN KEY FK_841E84D42E9074A8');
        $this->addSql('DROP INDEX UNIQ_841E84D4950B42A7 ON trace_mats');
        $this->addSql('DROP INDEX IDX_841E84D42E9074A8 ON trace_mats');
        $this->addSql('ALTER TABLE trace_mats ADD path_id INT DEFAULT NULL, ADD crimson_calyx_id INT DEFAULT NULL, ADD four_star_name VARCHAR(255) NOT NULL, ADD three_star_name VARCHAR(255) NOT NULL, ADD two_star_name VARCHAR(255) NOT NULL, ADD released TINYINT(1) NOT NULL, ADD announced TINYINT(1) NOT NULL, DROP trace_mats_path_id, DROP trace_mats_crimson_calyx_id, DROP trace_mats_four_star_name, DROP trace_mats_three_star_name, DROP trace_mats_two_star_name, DROP trace_mats_released, DROP trace_mats_announced');
        $this->addSql('ALTER TABLE trace_mats ADD CONSTRAINT FK_841E84D4D96C566B FOREIGN KEY (path_id) REFERENCES path (id)');
        $this->addSql('ALTER TABLE trace_mats ADD CONSTRAINT FK_841E84D445B610D FOREIGN KEY (crimson_calyx_id) REFERENCES crimson_calyx (id)');
        $this->addSql('CREATE INDEX IDX_841E84D4D96C566B ON trace_mats (path_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_841E84D445B610D ON trace_mats (crimson_calyx_id)');
        $this->addSql('ALTER TABLE type DROP FOREIGN KEY FK_8CDE57297C98B8C7');
        $this->addSql('DROP INDEX UNIQ_8CDE57297C98B8C7 ON type');
        $this->addSql('ALTER TABLE type CHANGE type_icon_id icon_id INT DEFAULT NULL, CHANGE type_name name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE type ADD CONSTRAINT FK_8CDE572954B9D732 FOREIGN KEY (icon_id) REFERENCES media (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8CDE572954B9D732 ON type (icon_id)');
        $this->addSql('ALTER TABLE weekly_mat DROP FOREIGN KEY FK_834A6167E10ED1CC');
        $this->addSql('ALTER TABLE weekly_mat DROP FOREIGN KEY FK_834A61678F9B3BF4');
        $this->addSql('DROP INDEX UNIQ_834A61678F9B3BF4 ON weekly_mat');
        $this->addSql('DROP INDEX UNIQ_834A6167E10ED1CC ON weekly_mat');
        $this->addSql('ALTER TABLE weekly_mat ADD icon_id INT DEFAULT NULL, ADD echo_of_war_id INT DEFAULT NULL, ADD released TINYINT(1) NOT NULL, ADD announced TINYINT(1) NOT NULL, DROP weekly_mat_icon_id, DROP weekly_mat_echo_of_war_id, DROP weekly_mat_released, DROP weekly_mat_announced, CHANGE weekly_mat_name name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE weekly_mat ADD CONSTRAINT FK_834A616754B9D732 FOREIGN KEY (icon_id) REFERENCES media (id)');
        $this->addSql('ALTER TABLE weekly_mat ADD CONSTRAINT FK_834A61676511E278 FOREIGN KEY (echo_of_war_id) REFERENCES echo_of_war (id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_834A616754B9D732 ON weekly_mat (icon_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_834A61676511E278 ON weekly_mat (echo_of_war_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE character_eidolons_media (character_eidolons_id INT NOT NULL, media_id INT NOT NULL, INDEX IDX_90003B1E18E42D5D (character_eidolons_id), INDEX IDX_90003B1EEA9FDD75 (media_id), PRIMARY KEY(character_eidolons_id, media_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE character_eidolons_media ADD CONSTRAINT FK_90003B1EEA9FDD75 FOREIGN KEY (media_id) REFERENCES media (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE character_eidolons_media ADD CONSTRAINT FK_90003B1E18E42D5D FOREIGN KEY (character_eidolons_id) REFERENCES character_eidolons (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ascension_mats ADD asc_mat_four_star_name VARCHAR(255) NOT NULL, ADD asc_mat_three_star_name VARCHAR(255) NOT NULL, ADD asc_mat_two_star_name VARCHAR(255) NOT NULL, ADD asc_mat_released TINYINT(1) NOT NULL, ADD asc_mat_announced TINYINT(1) NOT NULL, DROP four_star_name, DROP three_star_name, DROP two_star_name, DROP released, DROP announced');
        $this->addSql('ALTER TABLE base_character DROP FOREIGN KEY FK_205621B9D96C566B');
        $this->addSql('ALTER TABLE base_character DROP FOREIGN KEY FK_205621B9C54C8C93');
        $this->addSql('ALTER TABLE base_character DROP FOREIGN KEY FK_205621B9CB5A3E01');
        $this->addSql('ALTER TABLE base_character DROP FOREIGN KEY FK_205621B910DA5845');
        $this->addSql('ALTER TABLE base_character DROP FOREIGN KEY FK_205621B9C136EA7E');
        $this->addSql('ALTER TABLE base_character DROP FOREIGN KEY FK_205621B949213874');
        $this->addSql('DROP INDEX IDX_205621B9D96C566B ON base_character');
        $this->addSql('DROP INDEX IDX_205621B9C54C8C93 ON base_character');
        $this->addSql('DROP INDEX IDX_205621B9CB5A3E01 ON base_character');
        $this->addSql('DROP INDEX IDX_205621B910DA5845 ON base_character');
        $this->addSql('DROP INDEX IDX_205621B9C136EA7E ON base_character');
        $this->addSql('DROP INDEX IDX_205621B949213874 ON base_character');
        $this->addSql('ALTER TABLE base_character ADD character_path_id INT DEFAULT NULL, ADD character_type_id INT DEFAULT NULL, ADD eidolons_id INT DEFAULT NULL, ADD character_asc_mats_id INT DEFAULT NULL, ADD character_boss_mat_id INT DEFAULT NULL, ADD character_weekly_mat_id INT DEFAULT NULL, ADD character_trace_mats_id INT DEFAULT NULL, ADD character_name VARCHAR(255) NOT NULL, ADD character_slug VARCHAR(255) NOT NULL, ADD character_rarity VARCHAR(255) NOT NULL, ADD character_released TINYINT(1) NOT NULL, ADD character_announced TINYINT(1) NOT NULL, ADD character_release_version VARCHAR(255) DEFAULT NULL, ADD character_banner_name VARCHAR(255) DEFAULT NULL, DROP path_id, DROP type_id, DROP asc_mats_id, DROP boss_mat_id, DROP weekly_mat_id, DROP trace_mats_id, DROP name, DROP slug, DROP rarity, DROP released, DROP announced, DROP release_version, DROP banner_name, CHANGE release_date character_release_date DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE base_character ADD CONSTRAINT FK_205621B9F5875707 FOREIGN KEY (character_weekly_mat_id) REFERENCES weekly_mat (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE base_character ADD CONSTRAINT FK_205621B9CF3094AD FOREIGN KEY (character_asc_mats_id) REFERENCES ascension_mats (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE base_character ADD CONSTRAINT FK_205621B9B0C9D656 FOREIGN KEY (character_path_id) REFERENCES path (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE base_character ADD CONSTRAINT FK_205621B9ACE90CAE FOREIGN KEY (character_type_id) REFERENCES type (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE base_character ADD CONSTRAINT FK_205621B97D90850D FOREIGN KEY (character_trace_mats_id) REFERENCES trace_mats (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE base_character ADD CONSTRAINT FK_205621B91C8E87F1 FOREIGN KEY (eidolons_id) REFERENCES character_eidolons (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE base_character ADD CONSTRAINT FK_205621B914B0F2E9 FOREIGN KEY (character_boss_mat_id) REFERENCES boss_mat (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_205621B91C8E87F1 ON base_character (eidolons_id)');
        $this->addSql('CREATE INDEX IDX_205621B9B0C9D656 ON base_character (character_path_id)');
        $this->addSql('CREATE INDEX IDX_205621B9ACE90CAE ON base_character (character_type_id)');
        $this->addSql('CREATE INDEX IDX_205621B9CF3094AD ON base_character (character_asc_mats_id)');
        $this->addSql('CREATE INDEX IDX_205621B914B0F2E9 ON base_character (character_boss_mat_id)');
        $this->addSql('CREATE INDEX IDX_205621B9F5875707 ON base_character (character_weekly_mat_id)');
        $this->addSql('CREATE INDEX IDX_205621B97D90850D ON base_character (character_trace_mats_id)');
        $this->addSql('ALTER TABLE boss_mat DROP FOREIGN KEY FK_4139099754B9D732');
        $this->addSql('ALTER TABLE boss_mat DROP FOREIGN KEY FK_413909974EF5897C');
        $this->addSql('ALTER TABLE boss_mat DROP FOREIGN KEY FK_41390997C54C8C93');
        $this->addSql('DROP INDEX UNIQ_4139099754B9D732 ON boss_mat');
        $this->addSql('DROP INDEX UNIQ_413909974EF5897C ON boss_mat');
        $this->addSql('DROP INDEX IDX_41390997C54C8C93 ON boss_mat');
        $this->addSql('ALTER TABLE boss_mat ADD boss_mat_icon_id INT DEFAULT NULL, ADD boss_mat_stagnant_shadow_id INT DEFAULT NULL, ADD boss_mat_type_id INT DEFAULT NULL, ADD boss_mat_released TINYINT(1) NOT NULL, ADD boss_mat_announced TINYINT(1) NOT NULL, DROP icon_id, DROP stagnant_shadow_id, DROP type_id, DROP released, DROP announced, CHANGE name boss_mat_name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE boss_mat ADD CONSTRAINT FK_41390997D6CAE9E8 FOREIGN KEY (boss_mat_icon_id) REFERENCES media (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE boss_mat ADD CONSTRAINT FK_41390997D0FF67F FOREIGN KEY (boss_mat_stagnant_shadow_id) REFERENCES stagnant_shadow (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE boss_mat ADD CONSTRAINT FK_41390997473FB249 FOREIGN KEY (boss_mat_type_id) REFERENCES type (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_41390997D6CAE9E8 ON boss_mat (boss_mat_icon_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_41390997D0FF67F ON boss_mat (boss_mat_stagnant_shadow_id)');
        $this->addSql('CREATE INDEX IDX_41390997473FB249 ON boss_mat (boss_mat_type_id)');
        $this->addSql('ALTER TABLE character_eidolons DROP FOREIGN KEY FK_33089EC899CCA37C');
        $this->addSql('ALTER TABLE character_eidolons DROP FOREIGN KEY FK_33089EC854B9D732');
        $this->addSql('DROP INDEX IDX_33089EC899CCA37C ON character_eidolons');
        $this->addSql('DROP INDEX UNIQ_33089EC854B9D732 ON character_eidolons');
        $this->addSql('ALTER TABLE character_eidolons ADD eidolon_one JSON DEFAULT NULL, ADD eidolon_two JSON DEFAULT NULL, ADD eidolon_three JSON DEFAULT NULL, ADD eidolon_four JSON DEFAULT NULL, ADD eidolon_five JSON DEFAULT NULL, ADD eidolon_six JSON DEFAULT NULL, ADD eidolon_stop_point LONGTEXT DEFAULT NULL, DROP character_kit_id, DROP icon_id, DROP name, DROP number, DROP description, DROP pull_worth, DROP recommendation');
        $this->addSql('ALTER TABLE character_kit DROP FOREIGN KEY FK_133E438618777CEF');
        $this->addSql('DROP INDEX UNIQ_133E438618777CEF ON character_kit');
        $this->addSql('ALTER TABLE character_kit CHANGE talent_id character_talent_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE character_kit ADD CONSTRAINT FK_133E43869F27DED4 FOREIGN KEY (character_talent_id) REFERENCES character_talent (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_133E43869F27DED4 ON character_kit (character_talent_id)');
        $this->addSql('ALTER TABLE character_stories DROP FOREIGN KEY FK_F52E1D621136BE75');
        $this->addSql('DROP INDEX UNIQ_F52E1D621136BE75 ON character_stories');
        $this->addSql('ALTER TABLE character_stories CHANGE character_id character_stories_character_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE character_stories ADD CONSTRAINT FK_F52E1D6295FABCD7 FOREIGN KEY (character_stories_character_id) REFERENCES base_character (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_F52E1D6295FABCD7 ON character_stories (character_stories_character_id)');
        $this->addSql('ALTER TABLE character_voiceline DROP FOREIGN KEY FK_DAE759C81136BE75');
        $this->addSql('DROP INDEX IDX_DAE759C81136BE75 ON character_voiceline');
        $this->addSql('ALTER TABLE character_voiceline CHANGE character_id voiceline_character_id INT DEFAULT NULL, CHANGE name voiceline_name VARCHAR(255) NOT NULL, CHANGE content voiceline_content LONGTEXT DEFAULT NULL, CHANGE category voiceline_category VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE character_voiceline ADD CONSTRAINT FK_DAE759C8E37CC563 FOREIGN KEY (voiceline_character_id) REFERENCES base_character (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE INDEX IDX_DAE759C8E37CC563 ON character_voiceline (voiceline_character_id)');
        $this->addSql('ALTER TABLE crimson_calyx DROP FOREIGN KEY FK_21EE9C9764D218E');
        $this->addSql('DROP INDEX IDX_21EE9C9764D218E ON crimson_calyx');
        $this->addSql('ALTER TABLE crimson_calyx CHANGE location_id crimson_calyx_location_id INT DEFAULT NULL, CHANGE name crimson_calyx_name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE crimson_calyx ADD CONSTRAINT FK_21EE9C972F1B3052 FOREIGN KEY (crimson_calyx_location_id) REFERENCES location (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE INDEX IDX_21EE9C972F1B3052 ON crimson_calyx (crimson_calyx_location_id)');
        $this->addSql('ALTER TABLE echo_of_war DROP FOREIGN KEY FK_A4D428A554B9D732');
        $this->addSql('ALTER TABLE echo_of_war DROP FOREIGN KEY FK_A4D428A5261FB672');
        $this->addSql('ALTER TABLE echo_of_war DROP FOREIGN KEY FK_A4D428A564D218E');
        $this->addSql('DROP INDEX UNIQ_A4D428A554B9D732 ON echo_of_war');
        $this->addSql('DROP INDEX UNIQ_A4D428A5261FB672 ON echo_of_war');
        $this->addSql('DROP INDEX IDX_A4D428A564D218E ON echo_of_war');
        $this->addSql('ALTER TABLE echo_of_war ADD echo_of_war_icon_id INT DEFAULT NULL, ADD echo_of_war_boss_id INT DEFAULT NULL, ADD echo_of_war_location_id INT DEFAULT NULL, DROP icon_id, DROP boss_id, DROP location_id, CHANGE name echo_of_war_name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE echo_of_war ADD CONSTRAINT FK_A4D428A53206CF33 FOREIGN KEY (echo_of_war_icon_id) REFERENCES media (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE echo_of_war ADD CONSTRAINT FK_A4D428A540A0AE73 FOREIGN KEY (echo_of_war_boss_id) REFERENCES echos_boss (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE echo_of_war ADD CONSTRAINT FK_A4D428A56B48C239 FOREIGN KEY (echo_of_war_location_id) REFERENCES location (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A4D428A53206CF33 ON echo_of_war (echo_of_war_icon_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A4D428A540A0AE73 ON echo_of_war (echo_of_war_boss_id)');
        $this->addSql('CREATE INDEX IDX_A4D428A56B48C239 ON echo_of_war (echo_of_war_location_id)');
        $this->addSql('ALTER TABLE echos_boss DROP FOREIGN KEY FK_E715037254B9D732');
        $this->addSql('DROP INDEX UNIQ_E715037254B9D732 ON echos_boss');
        $this->addSql('ALTER TABLE echos_boss CHANGE icon_id echo_boss_icon_id INT DEFAULT NULL, CHANGE name echo_boss_name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE echos_boss ADD CONSTRAINT FK_E7150372B1EF9B71 FOREIGN KEY (echo_boss_icon_id) REFERENCES media (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E7150372B1EF9B71 ON echos_boss (echo_boss_icon_id)');
        $this->addSql('ALTER TABLE elite_enemy DROP FOREIGN KEY FK_40EEB32954B9D732');
        $this->addSql('DROP INDEX UNIQ_40EEB32954B9D732 ON elite_enemy');
        $this->addSql('ALTER TABLE elite_enemy CHANGE icon_id elite_enemy_icon_id INT DEFAULT NULL, CHANGE name elite_enemy_name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE elite_enemy ADD CONSTRAINT FK_40EEB329A3E838B4 FOREIGN KEY (elite_enemy_icon_id) REFERENCES media (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_40EEB329A3E838B4 ON elite_enemy (elite_enemy_icon_id)');
        $this->addSql('ALTER TABLE golden_calyx DROP FOREIGN KEY FK_2CDBA20B64D218E');
        $this->addSql('DROP INDEX IDX_2CDBA20B64D218E ON golden_calyx');
        $this->addSql('ALTER TABLE golden_calyx CHANGE location_id golden_calyx_location_id INT DEFAULT NULL, CHANGE name golden_calyx_name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE golden_calyx ADD CONSTRAINT FK_2CDBA20B434731FE FOREIGN KEY (golden_calyx_location_id) REFERENCES location (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE INDEX IDX_2CDBA20B434731FE ON golden_calyx (golden_calyx_location_id)');
        $this->addSql('ALTER TABLE light_cone DROP FOREIGN KEY FK_3CA80094D96C566B');
        $this->addSql('ALTER TABLE light_cone DROP FOREIGN KEY FK_3CA80094CB5A3E01');
        $this->addSql('ALTER TABLE light_cone DROP FOREIGN KEY FK_3CA8009449213874');
        $this->addSql('DROP INDEX IDX_3CA80094D96C566B ON light_cone');
        $this->addSql('DROP INDEX IDX_3CA80094CB5A3E01 ON light_cone');
        $this->addSql('DROP INDEX IDX_3CA8009449213874 ON light_cone');
        $this->addSql('ALTER TABLE light_cone ADD lc_path_id INT DEFAULT NULL, ADD lc_asc_mats_id INT DEFAULT NULL, ADD lc_trace_mats_id INT DEFAULT NULL, ADD lc_name VARCHAR(255) NOT NULL, ADD lc_slug VARCHAR(255) NOT NULL, ADD lc_rarity VARCHAR(255) NOT NULL, ADD lc_base_atk INT DEFAULT NULL, ADD lc_base_def INT DEFAULT NULL, ADD lc_base_hp INT DEFAULT NULL, ADD lc_story LONGTEXT DEFAULT NULL, ADD lc_skill_one LONGTEXT DEFAULT NULL, ADD lc_skill_two LONGTEXT DEFAULT NULL, ADD lc_skill_three LONGTEXT DEFAULT NULL, ADD lc_skill_four LONGTEXT DEFAULT NULL, ADD lc_skill_five LONGTEXT DEFAULT NULL, ADD lc_skill_name VARCHAR(255) DEFAULT NULL, ADD lc_announced TINYINT(1) NOT NULL, ADD lc_released TINYINT(1) NOT NULL, ADD lc_obtainable VARCHAR(255) NOT NULL, ADD lc_release_version VARCHAR(255) DEFAULT NULL, DROP path_id, DROP asc_mats_id, DROP trace_mats_id, DROP name, DROP slug, DROP rarity, DROP base_atk, DROP base_def, DROP base_hp, DROP story, DROP superimposition_one, DROP superimposition_two, DROP superimposition_three, DROP superimposition_four, DROP superimposition_five, DROP skill_name, DROP announced, DROP released, DROP obtainable, DROP release_version');
        $this->addSql('ALTER TABLE light_cone ADD CONSTRAINT FK_3CA8009485B95996 FOREIGN KEY (lc_path_id) REFERENCES path (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE light_cone ADD CONSTRAINT FK_3CA800942A989BC3 FOREIGN KEY (lc_asc_mats_id) REFERENCES ascension_mats (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE light_cone ADD CONSTRAINT FK_3CA8009416513B1D FOREIGN KEY (lc_trace_mats_id) REFERENCES trace_mats (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE INDEX IDX_3CA8009485B95996 ON light_cone (lc_path_id)');
        $this->addSql('CREATE INDEX IDX_3CA800942A989BC3 ON light_cone (lc_asc_mats_id)');
        $this->addSql('CREATE INDEX IDX_3CA8009416513B1D ON light_cone (lc_trace_mats_id)');
        $this->addSql('ALTER TABLE location DROP FOREIGN KEY FK_5E9E89CB54B9D732');
        $this->addSql('DROP INDEX UNIQ_5E9E89CB54B9D732 ON location');
        $this->addSql('ALTER TABLE location ADD location_name VARCHAR(255) NOT NULL, ADD location_world VARCHAR(255) NOT NULL, DROP name, DROP world, CHANGE icon_id location_icon_id INT DEFAULT NULL, CHANGE released location_released TINYINT(1) NOT NULL, CHANGE description location_description LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE location ADD CONSTRAINT FK_5E9E89CBBAFCC496 FOREIGN KEY (location_icon_id) REFERENCES media (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5E9E89CBBAFCC496 ON location (location_icon_id)');
        $this->addSql('ALTER TABLE media CHANGE name media_name VARCHAR(255) NOT NULL, CHANGE role image_role VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE normal_enemy DROP FOREIGN KEY FK_B638B9F354B9D732');
        $this->addSql('DROP INDEX UNIQ_B638B9F354B9D732 ON normal_enemy');
        $this->addSql('ALTER TABLE normal_enemy CHANGE icon_id normal_enemy_icon_id INT DEFAULT NULL, CHANGE name normal_enemy_name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE normal_enemy ADD CONSTRAINT FK_B638B9F3935657E1 FOREIGN KEY (normal_enemy_icon_id) REFERENCES media (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B638B9F3935657E1 ON normal_enemy (normal_enemy_icon_id)');
        $this->addSql('ALTER TABLE path DROP FOREIGN KEY FK_B548B0F54B9D732');
        $this->addSql('DROP INDEX UNIQ_B548B0F54B9D732 ON path');
        $this->addSql('ALTER TABLE path CHANGE icon_id path_icon_id INT DEFAULT NULL, CHANGE name path_name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE path ADD CONSTRAINT FK_B548B0F930FE11B FOREIGN KEY (path_icon_id) REFERENCES media (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_B548B0F930FE11B ON path (path_icon_id)');
        $this->addSql('ALTER TABLE stagnant_shadow DROP FOREIGN KEY FK_2D8BA4CC54B9D732');
        $this->addSql('ALTER TABLE stagnant_shadow DROP FOREIGN KEY FK_2D8BA4CC261FB672');
        $this->addSql('ALTER TABLE stagnant_shadow DROP FOREIGN KEY FK_2D8BA4CC64D218E');
        $this->addSql('DROP INDEX UNIQ_2D8BA4CC54B9D732 ON stagnant_shadow');
        $this->addSql('DROP INDEX UNIQ_2D8BA4CC261FB672 ON stagnant_shadow');
        $this->addSql('DROP INDEX IDX_2D8BA4CC64D218E ON stagnant_shadow');
        $this->addSql('ALTER TABLE stagnant_shadow ADD stagnant_shadow_icon_id INT DEFAULT NULL, ADD stagnant_shadow_boss_id INT DEFAULT NULL, ADD stagnant_shadow_location_id INT DEFAULT NULL, DROP icon_id, DROP boss_id, DROP location_id, CHANGE name stagnant_shadow_name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE stagnant_shadow ADD CONSTRAINT FK_2D8BA4CCF33A9CE4 FOREIGN KEY (stagnant_shadow_icon_id) REFERENCES media (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE stagnant_shadow ADD CONSTRAINT FK_2D8BA4CC819CFDA4 FOREIGN KEY (stagnant_shadow_boss_id) REFERENCES elite_enemy (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE stagnant_shadow ADD CONSTRAINT FK_2D8BA4CC21A15829 FOREIGN KEY (stagnant_shadow_location_id) REFERENCES location (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2D8BA4CCF33A9CE4 ON stagnant_shadow (stagnant_shadow_icon_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2D8BA4CC819CFDA4 ON stagnant_shadow (stagnant_shadow_boss_id)');
        $this->addSql('CREATE INDEX IDX_2D8BA4CC21A15829 ON stagnant_shadow (stagnant_shadow_location_id)');
        $this->addSql('ALTER TABLE trace_mats DROP FOREIGN KEY FK_841E84D4D96C566B');
        $this->addSql('ALTER TABLE trace_mats DROP FOREIGN KEY FK_841E84D445B610D');
        $this->addSql('DROP INDEX IDX_841E84D4D96C566B ON trace_mats');
        $this->addSql('DROP INDEX UNIQ_841E84D445B610D ON trace_mats');
        $this->addSql('ALTER TABLE trace_mats ADD trace_mats_path_id INT DEFAULT NULL, ADD trace_mats_crimson_calyx_id INT DEFAULT NULL, ADD trace_mats_four_star_name VARCHAR(255) NOT NULL, ADD trace_mats_three_star_name VARCHAR(255) NOT NULL, ADD trace_mats_two_star_name VARCHAR(255) NOT NULL, ADD trace_mats_released TINYINT(1) NOT NULL, ADD trace_mats_announced TINYINT(1) NOT NULL, DROP path_id, DROP crimson_calyx_id, DROP four_star_name, DROP three_star_name, DROP two_star_name, DROP released, DROP announced');
        $this->addSql('ALTER TABLE trace_mats ADD CONSTRAINT FK_841E84D4950B42A7 FOREIGN KEY (trace_mats_crimson_calyx_id) REFERENCES crimson_calyx (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE trace_mats ADD CONSTRAINT FK_841E84D42E9074A8 FOREIGN KEY (trace_mats_path_id) REFERENCES path (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_841E84D4950B42A7 ON trace_mats (trace_mats_crimson_calyx_id)');
        $this->addSql('CREATE INDEX IDX_841E84D42E9074A8 ON trace_mats (trace_mats_path_id)');
        $this->addSql('ALTER TABLE type DROP FOREIGN KEY FK_8CDE572954B9D732');
        $this->addSql('DROP INDEX UNIQ_8CDE572954B9D732 ON type');
        $this->addSql('ALTER TABLE type CHANGE icon_id type_icon_id INT DEFAULT NULL, CHANGE name type_name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE type ADD CONSTRAINT FK_8CDE57297C98B8C7 FOREIGN KEY (type_icon_id) REFERENCES media (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8CDE57297C98B8C7 ON type (type_icon_id)');
        $this->addSql('ALTER TABLE weekly_mat DROP FOREIGN KEY FK_834A616754B9D732');
        $this->addSql('ALTER TABLE weekly_mat DROP FOREIGN KEY FK_834A61676511E278');
        $this->addSql('DROP INDEX UNIQ_834A616754B9D732 ON weekly_mat');
        $this->addSql('DROP INDEX UNIQ_834A61676511E278 ON weekly_mat');
        $this->addSql('ALTER TABLE weekly_mat ADD weekly_mat_icon_id INT DEFAULT NULL, ADD weekly_mat_echo_of_war_id INT DEFAULT NULL, ADD weekly_mat_released TINYINT(1) NOT NULL, ADD weekly_mat_announced TINYINT(1) NOT NULL, DROP icon_id, DROP echo_of_war_id, DROP released, DROP announced, CHANGE name weekly_mat_name VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE weekly_mat ADD CONSTRAINT FK_834A6167E10ED1CC FOREIGN KEY (weekly_mat_echo_of_war_id) REFERENCES echo_of_war (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE weekly_mat ADD CONSTRAINT FK_834A61678F9B3BF4 FOREIGN KEY (weekly_mat_icon_id) REFERENCES media (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_834A61678F9B3BF4 ON weekly_mat (weekly_mat_icon_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_834A6167E10ED1CC ON weekly_mat (weekly_mat_echo_of_war_id)');
    }
}
